name: Django Tests with Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage (SQLite in memory)
        env:
          DJANGO_SETTINGS_MODULE: api.settings
        run: |
          coverage run manage.py test
          coverage report --fail-under=80 # O el porcentaje que decidas

